apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
    giantswarm.io/monitoring: "true"
  annotations:
    giantswarm.io/monitoring-path: "/metrics"
    giantswarm.io/monitoring-port: "8080"
    prometheus.io/scrape: "true"
spec:
  selector:
    {{- include "labels.selector" . | nindent 4 }}
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
