apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
spec:
  selector:
    {{- include "labels.selector" . | nindent 4 }}
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
