version: 2.1

orbs:
  architect: giantswarm/architect@4.36.0

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: irsa-operator
          resource_class: large
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          requires:
            - go-build
          filters:
            tags:
              only: /^v.*/
      - architect/push-to-app-catalog:
          context: "architect"
          executor: "app-build-suite"
          name: push-irsa-operator-to-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "irsa-operator"
          requires:
            - push-to-registries
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: aws-app-collection
          context: "architect"
          app_name: "irsa-operator"
          app_namespace: "giantswarm"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-irsa-operator-to-app-catalog
            - push-to-registries
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-capa-app-collection
          app_name: "irsa-operator"
          app_collection_repo: "capa-app-collection"
          requires:
            - push-irsa-operator-to-app-catalog
            - push-to-registries
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
