version: 2.1

orbs:
  architect: giantswarm/architect@4.28.1

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: irsa-operator
          resource_class: large
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-irsa-operator-to-quay
          image: "quay.io/giantswarm/irsa-operator"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/
      - architect/push-to-docker:
          context: "architect"
          name: push-irsa-operator-to-docker
          image: "docker.io/giantswarm/irsa-operator"
          username_envar: "DOCKER_USERNAME"
          password_envar: "DOCKER_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/
      - architect/push-to-docker:
          context: "architect"
          name: push-irsa-operator-to-aliyun
          image: "giantswarm-registry.cn-shanghai.cr.aliyuncs.com/giantswarm/irsa-operator"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: "architect"
          name: push-irsa-operator-to-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "irsa-operator"
          requires:
            - push-irsa-operator-to-quay
            - push-irsa-operator-to-docker
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: aws-app-collection
          context: "architect"
          app_name: "irsa-operator"
          app_namespace: "giantswarm"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-irsa-operator-to-quay
            - push-irsa-operator-to-docker
            - push-irsa-operator-to-aliyun
            - push-irsa-operator-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-capa-app-collection
          app_name: "irsa-operator"
          app_collection_repo: "capa-app-collection"
          requires:
            - push-irsa-operator-to-quay
            - push-irsa-operator-to-docker
            - push-irsa-operator-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
