aws:
  accessKeyID: accesskey
  secretAccessKey: secretkey
  region: region

capa: false
legacy: true

installation:
  name: name

image:
  name: "giantswarm/irsa-operator"
  tag: ""
registry:
  domain: gsoci.azurecr.io

pod:
  user:
    id: 1000
  group:
    id: 1000

resources:
  limits:
    cpu: 250m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 250Mi

# Add seccomp to pod security context
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

# Add seccomp to container security context
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
      - ALL

global:
  podSecurityStandards:
    enforced: false
